// Web Design Automation Factory - Production Build Exporter
// Compiles full semantic HTML5, scoped CSS, and packages everything client-side.

const Exporter = {
  // Main compilation script
  compileWorkspace(state) {
    const { 
      seoTitle, 
      seoDescription, 
      seoKeywords, 
      seoLanguage, 
      contactEmail,
      themePrimary,
      themeSecondary,
      themeAccent,
      themeBg,
      containerWidth,
      borderRadius,
      fontFamily,
      activeSections 
    } = state;

    // 1. Compile CSS Variables & Core Styles
    let compiledCSS = `/* ==========================================================================
   PRODUCTION CORE STYLE SHEET - GENERATED BY WEB DESIGN AUTOMATION FACTORY
   ========================================================================== */

@import url('https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;500&family=Outfit:wght@300;400;500;600;700;800&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap');

:root {
  --color-primary: ${themePrimary};
  --color-primary-glow: ${this.hexToRgba(themePrimary, 0.25)};
  --color-secondary: ${themeSecondary};
  --color-secondary-glow: ${this.hexToRgba(themeSecondary, 0.25)};
  --color-accent: ${themeAccent};
  --color-accent-glow: ${this.hexToRgba(themeAccent, 0.25)};
  --color-bg: ${themeBg};
  --container-width: ${containerWidth}px;
  --border-radius: ${borderRadius}px;
  --font-family: '${fontFamily}', sans-serif;
  --color-text: #ffffff;
  --color-text-muted: #9ca3af;
}

* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

html {
  scroll-behavior: smooth;
  background-color: var(--color-bg);
}

body {
  font-family: var(--font-family);
  color: var(--color-text);
  background-color: var(--color-bg);
  line-height: 1.5;
  overflow-x: hidden;
}

/* Custom Scrollbar */
::-webkit-scrollbar {
  width: 8px;
}
::-webkit-scrollbar-track {
  background: var(--color-bg);
}
::-webkit-scrollbar-thumb {
  background: rgba(255, 255, 255, 0.08);
  border-radius: 4px;
}
::-webkit-scrollbar-thumb:hover {
  background: var(--color-primary);
}
`;

    // 2. Append scoped CSS for active components
    const compiledSectionIds = new Set();
    activeSections.forEach(section => {
      const comp = WebComponents[section.componentId];
      if (comp && !compiledSectionIds.has(section.componentId)) {
        compiledSectionIds.add(section.componentId);
        compiledCSS += `\n/* Component: ${comp.name} */\n${comp.css}\n`;
      }
    });

    // 3. Compile HTML structure
    let sectionsHTML = '';
    activeSections.forEach(section => {
      const comp = WebComponents[section.componentId];
      if (comp) {
        let sectionHtml = comp.html;
        
        // Dynamically configure contact form Formspree action & emails
        if (section.componentId === 'contact') {
          const emailTarget = contactEmail.trim() || 'your-email@example.com';
          sectionHtml = sectionHtml.replace('{{CONTACT_EMAIL}}', emailTarget);
        }

        // Standardize IDs for specific section instances
        sectionsHTML += `\n<!-- Section: ${comp.name} -->\n${sectionHtml.trim()}\n`;
      }
    });

    // 4. Construct complete index.html skeleton
    const compiledHTML = `<!DOCTYPE html>
<html lang="${seoLanguage || 'en'}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${this.escapeHtml(seoTitle || 'Automated Web Design Factory')}</title>
  
  <!-- SEO Metadata -->
  <meta name="description" content="${this.escapeHtml(seoDescription || 'Custom Landing Page')}">
  <meta name="keywords" content="${this.escapeHtml(seoKeywords || 'automation, dynamic, clean')}">
  
  <!-- OpenGraph Metadata -->
  <meta property="og:title" content="${this.escapeHtml(seoTitle || 'Automated Web Design Factory')}">
  <meta property="og:description" content="${this.escapeHtml(seoDescription || 'Custom Landing Page')}">
  <meta property="og:type" content="website">
  
  <!-- Main Production Stylesheet -->
  <link rel="stylesheet" href="css/styles.css">
</head>
<body>

  <!-- Generated Sections Canvas -->
  ${sectionsHTML.trim()}

  <!-- Core Client-Side Interactivity Script -->
  <script>
    document.addEventListener('DOMContentLoaded', () => {
      // Mobile Navbar Interactive Trigger
      const mobileToggle = document.querySelector('.mobile-toggle');
      const navLinks = document.querySelector('.nav-links');
      const navActions = document.querySelector('.nav-actions');
      
      if (mobileToggle) {
        mobileToggle.addEventListener('click', () => {
          const isActive = navLinks.classList.toggle('active');
          if (navActions) navActions.classList.toggle('active');
          
          // Animate hamburger lines
          const spans = mobileToggle.querySelectorAll('span');
          if (isActive) {
            spans[0].style.transform = 'rotate(45deg) translate(5px, 5px)';
            spans[1].style.opacity = '0';
            spans[2].style.transform = 'rotate(-45deg) translate(5px, -5px)';
          } else {
            spans[0].style.transform = 'none';
            spans[1].style.opacity = '1';
            spans[2].style.transform = 'none';
          }
        });
      }

      // Smooth scroll anchors integration
      document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function (e) {
          e.preventDefault();
          const target = document.querySelector(this.getAttribute('href'));
          if (target) {
            target.scrollIntoView({
              behavior: 'smooth'
            });
            // Close mobile menu if open
            if (navLinks && navLinks.classList.contains('active')) {
              navLinks.classList.remove('active');
              if (navActions) navActions.classList.remove('active');
              const spans = mobileToggle.querySelectorAll('span');
              spans[0].style.transform = 'none';
              spans[1].style.opacity = '1';
              spans[2].style.transform = 'none';
            }
          }
        });
      });
    });
  </script>
</body>
</html>`;

    return { html: compiledHTML, css: compiledCSS };
  },

  // Helper: Hex color parser to RGBA string for canvas mesh styling overrides
  hexToRgba(hex, alpha) {
    let c;
    if (/^#([A-Fa-f0-9]{3}){1,2}$/.test(hex)) {
      c = hex.substring(1).split('');
      if (c.length === 3) {
        c = [c[0], c[0], c[1], c[1], c[2], c[2]];
      }
      c = '0x' + c.join('');
      return `rgba(${(c >> 16) & 255}, ${(c >> 8) & 255}, ${c & 255}, ${alpha})`;
    }
    return hex;
  },

  // Helper: HTML escaper for header variables
  escapeHtml(string) {
    return String(string)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  },

  // Native Client ZIP Downloader triggers
  downloadProductionZip(state) {
    if (typeof JSZip === 'undefined') {
      alert('JSZip library has not completed loading. Initiating single-file HTML fallback download.');
      this.downloadHtmlFallback(state);
      return;
    }

    const { html, css } = this.compileWorkspace(state);
    const zip = new JSZip();

    // Create /dist matching specifications
    const distFolder = zip.folder('dist');
    distFolder.file('index.html', html);
    distFolder.folder('css').file('styles.css', css);

    zip.generateAsync({ type: 'blob' }).then(content => {
      const element = document.createElement('a');
      element.href = URL.createObjectURL(content);
      element.download = 'web-design-automation-factory-dist.zip';
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);
    }).catch(err => {
      console.error('ZIP generation failed:', err);
      this.downloadHtmlFallback(state);
    });
  },

  // Fallback single-file combined compilation download
  downloadHtmlFallback(state) {
    const { html, css } = this.compileWorkspace(state);
    
    // Inject the CSS styles block in head for a functional standalone single file
    const styledHtml = html.replace(
      '<link rel="stylesheet" href="css/styles.css">',
      `<style>\n${css}\n</style>`
    );

    const element = document.createElement('a');
    const file = new Blob([styledHtml], { type: 'text/html' });
    element.href = URL.createObjectURL(file);
    element.download = 'index-standalone.html';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  }
};
