// Web Design Automation Factory - Production Build Exporter
// Compiles full semantic HTML5, scoped CSS, and packages everything client-side.

const Exporter = {
  compileWorkspace(appState) {
    const theme = INDUSTRIES[appState.industry] || INDUSTRIES.saas;
    const businessName = appState.businessName || 'Our Business';
    const contactEmail = appState.contactEmail || 'info@example.com';
    const activeSections = appState.activeSections || [];

    // 1. Compile CSS Variables & Core Styles
    let compiledCSS = `/* Production Build - Generated by Web Design Automation Factory */
@import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&display=swap');

:root {
  --color-primary: ${theme.primary};
  --color-secondary: ${theme.secondary};
  --color-accent: ${theme.accent};
  --color-bg: ${theme.background};
  --color-text: #ffffff;
  --color-text-muted: #9ca3af;
  --color-primary-glow: rgba(139, 92, 246, 0.3);
  --color-accent-glow: rgba(6, 182, 212, 0.2);
  --font-family: 'Outfit', sans-serif;
  --container-width: 1200px;
  --border-radius: 8px;
}

* { box-sizing: border-box; margin: 0; padding: 0; }
html { scroll-behavior: smooth; background-color: var(--color-bg); }
body { font-family: var(--font-family); color: var(--color-text); background: linear-gradient(180deg, #0a0b13, var(--color-bg)); line-height: 1.5; overflow-x: hidden; }
a { color: inherit; text-decoration: none; }
button, input, textarea { font-family: inherit; }
::-webkit-scrollbar { width: 8px; }
::-webkit-scrollbar-track { background: var(--color-bg); }
::-webkit-scrollbar-thumb { background: rgba(255, 255, 255, 0.08); border-radius: 4px; }
::-webkit-scrollbar-thumb:hover { background: var(--color-primary); }
`;

    // 2. Collect component CSS
    const compiledSectionIds = new Set();
    activeSections.forEach(sectionId => {
      const comp = WebComponents[sectionId];
      if (comp && !compiledSectionIds.has(sectionId)) {
        compiledSectionIds.add(sectionId);
        compiledCSS += `\n/* Component: ${comp.name} */\n${comp.css}\n`;
      }
    });

    // 3. Compile HTML with token resolution
    const resolvedTokens = {
      BUSINESS_NAME: businessName,
      CONTACT_EMAIL: contactEmail,
      HERO_CTA: appState.sourceMetadata?.brand?.cta_text || 'Get Started',
      PRIMARY_COLOR: theme.primary,
      ACCENT_COLOR: theme.accent,
      SECONDARY_COLOR: theme.secondary
    };

    let sectionsHTML = '';
    activeSections.forEach(sectionId => {
      const comp = WebComponents[sectionId];
      if (comp) {
        const rendered = renderComponent(sectionId, resolvedTokens);
        sectionsHTML += `\n<!-- Section: ${comp.name} -->\n${rendered.html.trim()}\n`;
      }
    });

    // 4. Construct complete HTML
    const compiledHTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${this.escapeHtml(businessName)} - Premium Web Design</title>
  <meta name="description" content="Discover ${this.escapeHtml(businessName)}. Premium digital solutions and services.">
  <meta property="og:title" content="${this.escapeHtml(businessName)}">
  <meta property="og:type" content="website">
  <style>
${compiledCSS}
  </style>
</head>
<body>
${sectionsHTML.trim()}

  <script>
    document.addEventListener('DOMContentLoaded', () => {
      const mobileToggle = document.querySelector('.mobile-toggle');
      const navLinks = document.querySelector('.nav-links');
      const navActions = document.querySelector('.nav-actions');

      if (mobileToggle) {
        mobileToggle.addEventListener('click', () => {
          const isActive = navLinks?.classList.toggle('active');
          navActions?.classList.toggle('active');
          const spans = mobileToggle.querySelectorAll('span');
          if (isActive) {
            spans[0].style.transform = 'rotate(45deg) translate(5px, 5px)';
            spans[1].style.opacity = '0';
            spans[2].style.transform = 'rotate(-45deg) translate(5px, -5px)';
          } else {
            spans[0].style.transform = 'none';
            spans[1].style.opacity = '1';
            spans[2].style.transform = 'none';
          }
        });
      }

      document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', (e) => {
          e.preventDefault();
          const target = document.querySelector(anchor.getAttribute('href'));
          if (target) target.scrollIntoView({ behavior: 'smooth' });
        });
      });
    });
  </script>
</body>
</html>`;

    return { html: compiledHTML, css: compiledCSS };
  },

  escapeHtml(string) {
    return String(string).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#039;');
  },

  downloadProductionZip(appState) {
    if (typeof JSZip === 'undefined') {
      alert('JSZip unavailable. Downloading as single HTML file.');
      this.downloadHtmlFallback(appState);
      return;
    }

    const { html } = this.compileWorkspace(appState);
    const zip = new JSZip();
    zip.file('index.html', html);

    zip.generateAsync({ type: 'blob' }).then(content => {
      const link = document.createElement('a');
      link.href = URL.createObjectURL(content);
      link.download = 'web-design.zip';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    }).catch(err => {
      console.error('ZIP generation failed:', err);
      this.downloadHtmlFallback(appState);
    });
  },

  downloadHtmlFallback(appState) {
    const { html } = this.compileWorkspace(appState);
    const link = document.createElement('a');
    link.href = URL.createObjectURL(new Blob([html], { type: 'text/html' }));
    link.download = 'index.html';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
};

