// Web Design Automation Factory — Production Build Exporter (FIXED v2.0)
// FIX #3: ZIP now contains self-contained CSS (no broken external link)
// FIX #4+5: {{CONTACT_EMAIL}} replaced with replaceAll() on all occurrences

const Exporter = {
  compileWorkspace(state) {
    const {
      seoTitle, seoDescription, seoKeywords, seoLanguage, contactEmail,
      themePrimary, themeSecondary, themeAccent, themeBg,
      containerWidth, borderRadius, fontFamily, activeSections
    } = state;

    // 1. Compile CSS Variables + Core Styles
    let compiledCSS = `/* ==========================================================================
   PRODUCTION CORE STYLE SHEET — GENERATED BY AURA AUTONOMOUS WEB DESIGNER ENGINE
   ========================================================================== */

@import url('https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;500&family=Outfit:wght@300;400;500;600;700;800&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap');

:root {
  --color-primary: ${themePrimary};
  --color-primary-glow: ${this.hexToRgba(themePrimary, 0.25)};
  --color-secondary: ${themeSecondary};
  --color-secondary-glow: ${this.hexToRgba(themeSecondary, 0.25)};
  --color-accent: ${themeAccent};
  --color-accent-glow: ${this.hexToRgba(themeAccent, 0.25)};
  --color-bg: ${themeBg};
  --container-width: ${containerWidth}px;
  --border-radius: ${borderRadius}px;
  --font-family: '${fontFamily}', sans-serif;
  --color-text: #ffffff;
  --color-text-muted: #9ca3af;
}

* { box-sizing: border-box; margin: 0; padding: 0; }

html { scroll-behavior: smooth; background-color: var(--color-bg); }

body {
  font-family: var(--font-family);
  color: var(--color-text);
  background-color: var(--color-bg);
  line-height: 1.5;
  overflow-x: hidden;
}

/* Motion Library Keyframes */
@keyframes motion-glow-pulse {
  0%, 100% { box-shadow: 0 0 12px 0px var(--glow-color, var(--color-primary)); }
  50% { box-shadow: 0 0 28px 6px var(--glow-color, var(--color-primary)); }
}
@keyframes motion-float {
  0%, 100% { transform: translateY(0px); }
  50% { transform: translateY(-8px); }
}
@keyframes motion-shimmer {
  0% { background-position: -200% center; }
  100% { background-position: 200% center; }
}

/* Custom Scrollbar */
::-webkit-scrollbar { width: 8px; }
::-webkit-scrollbar-track { background: var(--color-bg); }
::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.08); border-radius: 4px; }
::-webkit-scrollbar-thumb:hover { background: var(--color-primary); }
`;

    // 2. Append scoped component CSS (deduplicated)
    const compiledSectionIds = new Set();
    activeSections.forEach(section => {
      const comp = WebComponents[section.componentId];
      if (comp && !compiledSectionIds.has(section.componentId)) {
        compiledSectionIds.add(section.componentId);
        compiledCSS += `\n/* Component: ${comp.name} */\n${comp.css}\n`;
      }
    });

    // 3. Compile HTML sections
    // FIX #4+5: Use replaceAll to handle cloned contact sections with multiple {{CONTACT_EMAIL}}
    const emailTarget = (contactEmail || '').trim() || 'your-email@example.com';
    let sectionsHTML = '';
    activeSections.forEach(section => {
      const comp = WebComponents[section.componentId];
      if (comp) {
        // Motion library annotation
        let sectionHtml = MotionLib ? MotionLib.annotateHTML(comp.html) : comp.html;
        // Replace ALL occurrences of the placeholder (FIX #4 & #5)
        sectionHtml = sectionHtml.replaceAll('{{CONTACT_EMAIL}}', emailTarget);
        sectionsHTML += `\n<!-- Section: ${comp.name} -->\n${sectionHtml.trim()}\n`;
      }
    });

    // 4. Inline motion observer script for exported file
    const motionScript = `
    // Motion Library — Entrance Animations
    (function() {
      const io = new IntersectionObserver((entries) => {
        entries.forEach(e => {
          if (e.isIntersecting) {
            const el = e.target;
            const delay = parseFloat(el.dataset.motionDelay || '0') * 1000;
            setTimeout(() => {
              el.style.transition = 'opacity 0.6s ease, transform 0.6s cubic-bezier(0.16,1,0.3,1)';
              el.style.opacity = '1';
              el.style.transform = 'none';
            }, delay);
            io.unobserve(el);
          }
        });
      }, { threshold: 0.1 });
      document.querySelectorAll('[data-motion]').forEach(el => {
        el.style.opacity = '0';
        if (el.dataset.motion === 'fade-up') el.style.transform = 'translateY(24px)';
        if (el.dataset.motion === 'fade-left') el.style.transform = 'translateX(-32px)';
        if (el.dataset.motion === 'scale-in') el.style.transform = 'scale(0.92)';
        io.observe(el);
      });
    })();`;

    // 5. Construct full HTML
    // FIX #3: CSS is now embedded inline (no external link) for self-contained export
    const compiledHTML = `<!DOCTYPE html>
<html lang="${this.escapeHtml(seoLanguage || 'en')}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${this.escapeHtml(seoTitle || 'Automated Web Design')}</title>
  <meta name="description" content="${this.escapeHtml(seoDescription || '')}">
  <meta name="keywords" content="${this.escapeHtml(seoKeywords || '')}">
  <meta property="og:title" content="${this.escapeHtml(seoTitle || '')}">
  <meta property="og:description" content="${this.escapeHtml(seoDescription || '')}">
  <meta property="og:type" content="website">
  <style>
${compiledCSS}
  </style>
</head>
<body>

${sectionsHTML.trim()}

  <script>
    document.addEventListener('DOMContentLoaded', () => {
      // Mobile Navbar
      const mobileToggle = document.querySelector('.mobile-toggle');
      const navLinks = document.querySelector('.nav-links');
      const navActions = document.querySelector('.nav-actions');
      if (mobileToggle) {
        mobileToggle.addEventListener('click', () => {
          const isActive = navLinks && navLinks.classList.toggle('active');
          if (navActions) navActions.classList.toggle('active');
          const spans = mobileToggle.querySelectorAll('span');
          if (isActive) {
            spans[0].style.transform = 'rotate(45deg) translate(5px, 5px)';
            spans[1].style.opacity = '0';
            spans[2].style.transform = 'rotate(-45deg) translate(5px, -5px)';
          } else {
            spans[0].style.transform = 'none';
            spans[1].style.opacity = '1';
            spans[2].style.transform = 'none';
          }
        });
      }
      // Smooth scroll
      document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function(e) {
          e.preventDefault();
          const target = document.querySelector(this.getAttribute('href'));
          if (target) {
            target.scrollIntoView({ behavior: 'smooth' });
            if (navLinks && navLinks.classList.contains('active')) {
              navLinks.classList.remove('active');
              if (navActions) navActions.classList.remove('active');
              const spans = mobileToggle && mobileToggle.querySelectorAll('span');
              if (spans) { spans[0].style.transform = 'none'; spans[1].style.opacity = '1'; spans[2].style.transform = 'none'; }
            }
          }
        });
      });
      ${motionScript}
    });
  </script>
</body>
</html>`;

    return { html: compiledHTML, css: compiledCSS };
  },

  hexToRgba(hex, alpha) {
    let c;
    if (/^#([A-Fa-f0-9]{3}){1,2}$/.test(hex)) {
      c = hex.substring(1).split('');
      if (c.length === 3) c = [c[0], c[0], c[1], c[1], c[2], c[2]];
      c = '0x' + c.join('');
      return `rgba(${(c >> 16) & 255}, ${(c >> 8) & 255}, ${c & 255}, ${alpha})`;
    }
    return `rgba(139,92,246,${alpha})`; // safe fallback
  },

  escapeHtml(string) {
    return String(string)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  },

  // FIX #3: ZIP now contains separate CSS file that IS referenced correctly
  // AND fallback single-file always works because HTML is inline-styled
  downloadProductionZip(state) {
    if (typeof JSZip === 'undefined') {
      Toast.show('JSZip not loaded — downloading standalone HTML', 'warning');
      this.downloadHtmlFallback(state);
      return;
    }

    const { html, css } = this.compileWorkspace(state);
    const zip = new JSZip();
    const distFolder = zip.folder('dist');

    // Create a version with external CSS reference for the ZIP
    const htmlWithExternal = html.replace(
      '<style>\n' + css + '\n  </style>',
      '<link rel="stylesheet" href="css/styles.css">'
    );

    distFolder.file('index.html', htmlWithExternal);
    distFolder.folder('css').file('styles.css', css);
    distFolder.file('index-standalone.html', html); // Self-contained fallback always included

    // Include brand manifest
    try {
      distFolder.file('brand-manifest.json', BrandManifest.toJSON());
    } catch (_) {}

    zip.generateAsync({ type: 'blob' }).then(content => {
      const a = document.createElement('a');
      a.href = URL.createObjectURL(content);
      a.download = 'aura-production-dist.zip';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(a.href);
      Toast.show('✅ Production ZIP downloaded', 'success');
    }).catch(err => {
      console.error('ZIP error:', err);
      this.downloadHtmlFallback(state);
    });
  },

  downloadHtmlFallback(state) {
    const { html } = this.compileWorkspace(state);
    // HTML already has inline CSS — no replacement needed
    const a = document.createElement('a');
    const file = new Blob([html], { type: 'text/html' });
    a.href = URL.createObjectURL(file);
    a.download = 'index-standalone.html';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(a.href);
    Toast.show('✅ Standalone HTML downloaded', 'success');
  }
};
