#!/usr/bin/env node
/**
 * Web Design Automation Factory - Hardened Variable Generator
 * Validates inputs, handles fallbacks, replaces placeholder tokens, and compiles production distribution files.
 */

const fs = require('fs');
const path = require('path');

// 1. Resolve Input Variables & Environment Fallbacks
// We parse inputs from environment variables, allowing frictionless CI/CD mapping.
const rawBusinessName = process.env.BUSINESS_NAME || '';
const rawContactEmail = process.env.CONTACT_EMAIL || '';
const rawFormspreeHash = process.env.FORMSPREE_HASH || '';

// Hardened Variable Input Schema Check
// If parsed parameters return empty or missing, apply explicit, polished generic strings
const businessName = rawBusinessName.trim() ? rawBusinessName.trim() : 'Our Services';
const contactEmail = rawContactEmail.trim() ? rawContactEmail.trim() : 'info@domain.com';
const formspreeHash = rawFormspreeHash.trim();

// Derive a clean domain name for email placeholders
const cleanDomain = businessName.toLowerCase().replace(/[^a-z0-9]/g, '') || 'domain';
const businessDomain = `${cleanDomain}.com`;

console.log('[*] Hardened Variable Input Check Completed:');
console.log(`    - Business Name: "${businessName}" (Raw: "${rawBusinessName}")`);
console.log(`    - Contact Email: "${contactEmail}" (Raw: "${rawContactEmail}")`);
console.log(`    - Formspree Hash: "${formspreeHash || 'None'}"`);

// 2. Read Brand Colors JSON (generated by Python crawler extract_brand.py)
let brandColors = {
  primary: '#8b5cf6',   // Purple default
  secondary: '#f43f5e', // Rose default
  accent: '#06b6d4',    // Cyan default
  bg: '#06050b'         // Dark default
};

const brandJsonPath = path.join(process.cwd(), 'brand_colors.json');
if (fs.existsSync(brandJsonPath)) {
  try {
    const rawData = fs.readFileSync(brandJsonPath, 'utf8');
    const parsed = JSON.parse(rawData);
    brandColors = { ...brandColors, ...parsed };
    console.log(`[✓] Loaded brand color parameters:`, brandColors);
  } catch (err) {
    console.log(`[!] Failed to parse brand_colors.json: ${err.message}. Using defaults.`);
  }
} else {
  console.log('[!] brand_colors.json not found. Deploying system defaults.');
}

// 3. Read Blueprint HTML template
const templatePath = path.join(process.cwd(), 'templates', 'master-landing-page', 'index.html');
if (!fs.existsSync(templatePath)) {
  console.error(`[ERROR] Blueprint template not found at: ${templatePath}`);
  process.exit(1);
}

let htmlContent = fs.readFileSync(templatePath, 'utf8');

// 4. Form Action Processing (Failsafe & Fall-Tolerant Resolution)
// Ensure lead generation form actions target Formspree if a hash is available.
// If no Formspree hash is present, fall back to a safe mailto: action.
let formAction = `mailto:${contactEmail}`;
if (formspreeHash) {
  // If the hash is a full URL, use it; otherwise, append to the standard endpoint
  formAction = formspreeHash.startsWith('http') 
    ? formspreeHash 
    : `https://formspree.io/f/${formspreeHash}`;
  console.log(`[✓] Mapping active Formspree action: "${formAction}"`);
} else {
  console.log(`[✓] Defaulting to safe mailto fallback action: "${formAction}"`);
}

// 5. Replace Placeholder Tokens
htmlContent = htmlContent
  .replace(/{{BUSINESS_NAME}}/g, businessName)
  .replace(/{{BUSINESS_DOMAIN}}/g, businessDomain)
  .replace(/{{CONTACT_EMAIL}}/g, contactEmail)
  .replace(/{{PRIMARY_COLOR}}/g, brandColors.primary)
  .replace(/{{ACCENT_COLOR}}/g, brandColors.accent)
  .replace(/{{SECONDARY_COLOR}}/g, brandColors.secondary)
  .replace(/{{BG_COLOR}}/g, brandColors.bg)
  // Dynamically substitute form action targets
  .replace('action="mailto:{{CONTACT_EMAIL}}"', `action="${formAction}"`);

// 6. Ensure dist folder structure exists
const distDir = path.join(process.cwd(), 'dist');
if (!fs.existsSync(distDir)) {
  fs.mkdirSync(distDir, { recursive: true });
}

// 7. Write finalized distribution file
const outputPath = path.join(distDir, 'index.html');
try {
  fs.writeFileSync(outputPath, htmlContent, 'utf8');
  console.log(`[✓] Hardened distribution page generated successfully at: ${outputPath}`);
} catch (err) {
  console.error(`[ERROR] Failed to compile HTML distribution: ${err.message}`);
  process.exit(1);
}
